### ISSUE TITLE
Some questions about Quick Start

### ISSUE THREAD

**Issue by pddpd** [neoddish/rfm-cli#8]
I install rfm following by [Quick Start](https://github.com/neoddish/rfm-cli/wiki/Quick-Start).
After running `npm install -g rfm-cli`, I run `rfm --target rfmproject`, but get `command not found: rfm`
![image](https://user-images.githubusercontent.com/15177000/167545310-c3273c8a-63c4-4b49-86de-a9bd60f5338b.png)

And for `manifest`, w stands for webpack, r stands for rollup ... What if there are packages with the same initials? It may be clearer to use package's full name with character connecting and avoid repeat.

**Comment by neoddish** [comment]
will fix in 0.1.0-alpha.3
